# Base configs
baseurl: "https://michealcheery.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Michał Chechelski"
subtitle: "See the world through my eyes!"
author: "Michał Chechelski"
header:
 title: "Photography"
 subtitle: "by Michał Chechelski"
footer:
 name: "Hey there, my name is Michał"
 bio: "I am TODO"
 github: "Want a website like this for yourself for free? github.com/michealcheery/photography"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
